# Implemente uma função Python para cada uma das seguintes métricas de regressão:


*   MAE
*   MSE
*   RMSE

 Cada função deve receber valores reais (y) e valores preditos (y_pred) como parâmetros de entrada e retornar o valor calculado da métrica. Esse parâmetros podem ser arrays do numpy ou DataFrames do Pandas. O ideal é realizar as operações de forma vetorizada, evitando acessar cada célula individualmente. Não usar as implementações já existentes do Scikit-Learn.






In [14]:
import pandas as pd
import numpy as np

In [28]:
y = [1,4]
t_pred = [3,4]

In [41]:
def calculateMAE(y_true,y_pred):
   mae=np.sum(np.absolute(y_true - y_pred)) / y_true.shape[0]
   return mae

In [42]:
def calculateMSE(y_true,y_pred):
   mse=np.absolute(np.subtract(y_true, y_pred)**2).mean()
   return mse

In [43]:
def calculateRMSE(y_true,y_pred):
   rmse=np.sqrt(np.absolute(np.subtract(y_true, y_pred)**2).mean())
   return rm

In [44]:
mae = calculateMAE(y,t_pred)
mse = calculateMSE(y,t_pred)
rm = calculateRMSE(y,t_pred)
print("erro medio absoluto é : ",mae)
print("erro quadrático médio ",mse)
print("Raiz quadrada do erro-médio é aproximadamente : ",rm)

erro medio absoluto é :  1.0
erro quadrático médio  2.0
Raiz quadrada do erro-médio é aproximadamente :  1.4142135623730951


# Implemente uma função do Python para dividir de forma randomizada o dataset entre treino e teste. A função recebe como parâmetros:



1.   X - matriz com features
2.   y - vetor com rótulos
3.   perc_treino - percentual dos dados usados para treino
4.   seed - semente de randomização

A função deve retornar: X_train, y_train, X_test, y_test.  Não usar as implementações já existentes do Scikit-Learn.


In [20]:
df=pd.read_csv('/content/housing.csv')

In [21]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [22]:
corr_matrix = df.corr()
corr_matrix["median_house_value"].sort_values(ascending=False)

median_house_value    1.000000
median_income         0.688075
total_rooms           0.134153
housing_median_age    0.105623
households            0.065843
total_bedrooms        0.049686
population           -0.024650
longitude            -0.045967
latitude             -0.144160
Name: median_house_value, dtype: float64

In [23]:
x=df.iloc[:,:10]
x

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [24]:
df.corr()

longitude  latitude  housing_median_age  total_rooms  \
longitude            1.000000 -0.924664           -0.108197     0.044568   
latitude            -0.924664  1.000000            0.011173    -0.036100   
housing_median_age  -0.108197  0.011173            1.000000    -0.361262   
total_rooms          0.044568 -0.036100           -0.361262     1.000000   
total_bedrooms       0.069608 -0.066983           -0.320451     0.930380   
population           0.099773 -0.108785           -0.296244     0.857126   
households           0.055310 -0.071035           -0.302916     0.918484   
median_income       -0.015176 -0.079809           -0.119034     0.198050   
median_house_value  -0.045967 -0.144160            0.105623     0.134153   

                    total_bedrooms  population  households  median_income  \
longitude                 0.069608    0.099773    0.055310      -0.015176   
latitude                 -0.066983   -0.108785   -0.071035      -0.079809   
housing_median_age       -0.320451   -0.296244   -0.302916      -0.119034   
total_rooms               0.930380    0.857126    0.918484       0.198050   
total_bedrooms            1.000000    0.877747    0.979728      -0.007723   
population                0.877747    1.000000    0.907222       0.004834   
households                0.979728    0.907222    1.000000       0.013033   
median_income            -0.007723    0.004834    0.013033       1.000000   
median_house_value        0.049686   -0.024650    0.065843       0.688075   

                    median_house_value  
longitude                    -0.045967  
latitude                     -0.144160  
housing_median_age            0.105623  
total_rooms                   0.134153  
total_bedrooms                0.049686  
population                   -0.024650  
households                    0.065843  
median_income                 0.688075  
median_house_value            1.000000

In [25]:
y=df.iloc[:,8]
Y=y.values
Y

array([452600., 358500., 352100., ...,  92300.,  84700.,  89400.])

In [26]:
def split_train_test(data_values,data_labels,train_ratio,seed):
    qtd = X.shape[0]
    idx = np.random.RandomState(seed=seed).permutation(np.arange(qtd))
    qtd_train = int(qtd * train_ratio)
    idx_train = idx[0:qtd_train]
    idx_test  = idx[qtd_train:]
    if type(X) == np.ndarray:    # NumPy Array
        X_train   = X[idx_train]
        X_test    = X[idx_test]
        y_train   = y[idx_train]
        y_test    = y[idx_test]
    else:                        # Pandas DataFrame
        X_train   = X.iloc[idx_train]
        X_test    = X.iloc[idx_test]
        y_train   = y.iloc[idx_train]
        y_test    = y.iloc[idx_test]
        
    return X_train, X_test, y_train, y_test

In [27]:
X_train, X_test, y_train, y_test = split_train_test(x,Y,0.8,1)
print('X_TRAIN DOWN: ')
print(X_train)
print(end='\n')
print('X_TESTE DOWN: ')
print(X_test)
print(end='\n')
print('Y_TRAIN DOWN: ')
print(y_train)
print(end='\n')
print('Y_TEST DOWN: ')
print(y_test)

X_TRAIN DOWN: 
[[-118.36 34.06 39.0 ... 3.25 355000.0 '<1H OCEAN']
 [-119.78 36.78 37.0 ... 1.9784 70700.0 'INLAND']
 [-122.42 37.73 46.0 ... 4.0132 229400.0 'NEAR BAY']
 ...
 [-119.5 36.62 34.0 ... 2.2206 63400.0 'INLAND']
 [-122.68 38.76 29.0 ... 2.3125 67900.0 'INLAND']
 [-122.18 37.78 33.0 ... 3.875 225000.0 'NEAR BAY']]

X_TESTE DOWN: 
[[-117.08 33.12 43.0 ... 0.7054 137500.0 '<1H OCEAN']
 [-117.15 33.45 4.0 ... 4.6904 174200.0 '<1H OCEAN']
 [-117.13 32.69 36.0 ... 1.043 90100.0 'NEAR OCEAN']
 ...
 [-118.26 33.93 42.0 ... 1.1326 104800.0 '<1H OCEAN']
 [-117.16 33.73 10.0 ... 2.6322 140700.0 'INLAND']
 [-122.2 37.79 35.0 ... 2.3036 126000.0 'NEAR BAY']]

Y_TRAIN DOWN: 
[355000.  70700. 229400. ...  63400.  67900. 225000.]

Y_TEST DOWN: 
[137500. 174200.  90100. ... 104800. 140700. 126000.]
